biru/urls.py
#url routing
from biru.views import *
from django.urls import path

app_name = 'biru'

urlpatterns = [
    path('data_list_pertandingan', data_list_pertandingan, name='data_list_pertandingan'),
    path('dropdown_stadium', dropdown_stadium, name='dropdown_stadium'),
    path('data_list_waktu', data_list_waktu, name='data_list_waktu'),
    path('create_pertandingan', create_pertandingan, name='create_pertandingan'),
    path('delete', delete_pertandingan, name="delete_pertandingan"),
    path('submit_create_pertandingan', submit_create_pertandingan, name='submit_create_pertandingan'),
    path('update_dropdown_stadium', update_dropdown_stadium, name='update_dropdown_stadium'),
    path('update_create_pertandingan', update_create_pertandingan, name='update_create_pertandingan'),
    path('update_submit_create_pertandingan', update_submit_create_pertandingan, name='update_submit_create_pertandingan'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pink', include('pink.urls')),
    path('', include('putih.urls')),
    path('krem/', include('krem.urls')),
    path('putih/', include('putih.urls')),
    path('hijau/', include('hijau.urls')),
    path('biru/', include('biru.urls')),
]

biru/views.py
from django.shortcuts import render
import psycopg2
import psycopg2.extras
from django.conf import settings
from django.http import HttpResponseBadRequest, HttpResponse, HttpResponseRedirect, HttpResponseNotAllowed
from django.urls import reverse
from putih.decorators.logged_in_decorators import login_required_as_role
from django.shortcuts import redirect, render
from django.http import JsonResponse, QueryDict, HttpResponse
from django.core import serializers
from django.db import connection
from django.db.models.functions import datetime
from putih.decorators.logged_in_decorators import *
import uuid


# Create your views here.
conn = psycopg2.connect(database=settings.DATABASE_NAME, 
                        user=settings.DATABASE_USER, 
                        password=settings.DATABASE_PASSWORD,
                        host=settings.DATABASE_HOST, 
                        port=settings.DATABASE_PORT, 
                        )

cur = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)

def fetch(cursor):
    columns = [col[0] for col in cursor.description]
    return [dict(zip(columns, row)) for row in cursor.fetchall()]

def is_logged(request):
    try:
        request.session['email']
        return True
    except KeyError:
        return False

def data_list_pertandingan(request):
    # if request.method == 'GET' and is_logged(request):
    #     if request.session['is_admin_satgas']:
            query = """
                SELECT DISTINCT ON (B.id_pertandingan) B.id_pertandingan, A.nama_tim AS nama_tim_a, B.nama_tim AS nama_tim_b
                FROM tim_pertandingan AS A, tim_pertandingan AS B
                WHERE A.id_pertandingan = B.id_pertandingan AND A.nama_tim!=b.nama_tim;
            """
            
            # cursor = connection.cursor()
            cur.execute(query)
            data = fetch(cur)

            grup_a = data[:8]
            grup_b = data[8:16]

            response = {'data': data, 'data_1': grup_a, 'data_2': grup_b}
            print(response)
            return render(request, 'data_list_pertandingan.html', response)
        # return JsonResponse({'not_allowed': True})
    # return redirect("/authenticate/?next=/jadwal-faskes/")

def data_list_waktu(request):
            query = """
                SELECT DISTINCT ON (B.id_pertandingan) B.id_pertandingan, A.nama_tim AS nama_tim_a, B.nama_tim AS nama_tim_b
                FROM tim_pertandingan AS A, tim_pertandingan AS B
                WHERE A.id_pertandingan = B.id_pertandingan AND A.nama_tim!=b.nama_tim;
            """
            cur.execute(query)
            data = fetch(cur)

            grup_a = data[:8]
            grup_b = data[8:16]

            response = {'data': data, 'data_1': grup_a, 'data_2': grup_b}
            print(response)
            return render(request, 'data_list_waktu.html', response)

def dropdown_stadium(request):
            query = """
                SELECT S.Nama, S.id_stadium
                FROM Stadium AS S;
            """

            cur.execute(query)
            data = fetch(cur)
            response = {'data': data}
            print(response)
            
            return render(request, 'dropdown_stadium.html', response)

def create_pertandingan(request):
    if (request.method == "POST"):
        nama_stadium = request.POST.get("stadium")
        tanggal = request.POST.get("tanggal")
        print('haha')
        print(nama_stadium)
        print(tanggal)
        request.session['nama_stadium'] = nama_stadium
        request.session['tanggal'] = tanggal

        query_wasit = """
        SELECT nama_depan||' '||nama_belakang as nama, w.id_wasit
        FROM wasit as w, non_pemain
        WHERE NON_PEMAIN.id = w.id_wasit;
        """
        query_tim = f"select nama_tim from tim_manajer natural join peminjaman inner join stadium on peminjaman.id_stadium=stadium.id_stadium where stadium.id_stadium='{nama_stadium}';"

        # query_tim = f"select nama_tim from tim;"
        cur.execute(query_wasit)
        data_w = fetch(cur)

        cur.execute(query_tim)
        data_t = fetch(cur)
        # print(data_t)

        response = {'data_w': data_w, 'data_t': data_t, 'nama stadium': nama_stadium}
        # print(response)
        # print(nama_stadium)
        return render(request, 'create_pertandingan.html', response)
            
# INI BIKIN CREATE REALLL

def submit_create_pertandingan(request):
    if (request.method == "POST"):
        wasitutama = request.POST.get("wasitutama")
        wasitpembantu1 = request.POST.get("wasitpembantu1")
        wasitpembantu2 = request.POST.get("wasitpembantu2")
        wasitcadangan = request.POST.get("wasitcadangan")
        tim1 = request.POST.get("tim1")
        tim2 = request.POST.get("tim2")

        print(request.session)
        stadium = request.session.get('nama_stadium')
        tanggal = request.session.get('tanggal')
        print(stadium)

        try:
            psycopg2.extras.register_uuid()

            uuid_for_id_pertandingan = generate_uuid()
            print(uuid_for_id_pertandingan)
            print(stadium)

            cur.execute("INSERT INTO PERTANDINGAN VALUES(%s, %s, %s, %s)",
                        [uuid_for_id_pertandingan, tanggal, tanggal, stadium])
            cur.execute("INSERT INTO TIM_PERTANDINGAN VALUES(%s, %s, %s)", [tim1, uuid_for_id_pertandingan, 0])
            cur.execute("INSERT INTO TIM_PERTANDINGAN VALUES(%s, %s, %s)", [tim2, uuid_for_id_pertandingan, 0])
            cur.execute("INSERT INTO WASIT_BERTUGAS VALUES(%s, %s, %s)", [wasitutama, uuid_for_id_pertandingan, 'utama'])
            cur.execute("INSERT INTO WASIT_BERTUGAS VALUES(%s, %s, %s)", [wasitpembantu1, uuid_for_id_pertandingan, 'pembantu'])
            cur.execute("INSERT INTO WASIT_BERTUGAS VALUES(%s, %s, %s)", [wasitpembantu2, uuid_for_id_pertandingan, 'pembantu'])
            cur.execute("INSERT INTO WASIT_BERTUGAS VALUES(%s, %s, %s)", [wasitcadangan, uuid_for_id_pertandingan, 'cadangan'])
            conn.commit()

            return redirect(reverse('biru:data_list_pertandingan'))
        except Exception as e:
            conn.rollback()
            return HttpResponse(e)
    
    return HttpResponseNotAllowed("Invalid request method. Please use supported request method.")

# INI GENERATE ID

def generate_uuid():
    while (True):
        generated_uuid = uuid.uuid4()
        cur.execute("SELECT * FROM PERTANDINGAN WHERE id_pertandingan = %s", (generated_uuid,))
        lst_pertandingan = cur.fetchall()
        if (lst_pertandingan == []):
            return generated_uuid

# II KSAK LITAAAAAAAAAA

def delete_pertandingan(request):
	delete_tim_pertandingan(request.POST)
	return redirect("biru:data_list_pertandingan")

def delete_tim_pertandingan(data):
    query = f"""
    DELETE FROM rapat
    WHERE id_pertandingan = '{data['id_pertandingan']}';
    DELETE FROM tim_pertandingan
    WHERE id_pertandingan = '{data['id_pertandingan']}';
    DELETE FROM pembelian_tiket
    WHERE id_pertandingan = '{data['id_pertandingan']}';
    DELETE FROM wasit_bertugas
    WHERE id_pertandingan = '{data['id_pertandingan']}';
    DELETE FROM peristiwa
    WHERE id_pertandingan = '{data['id_pertandingan']}';
    DELETE FROM wasit_bertugas
    WHERE id_pertandingan = '{data['id_pertandingan']}';
    DELETE FROM pembelian_tiket
    WHERE id_pertandingan = '{data['id_pertandingan']}';
    DELETE FROM pertandingan
    WHERE id_pertandingan = '{data['id_pertandingan']}';
    """
    cur.execute(query)
    conn.commit()

# INI MAU COBA UPDATEEEEEEEEE

def update_dropdown_stadium(request):
    if (request.method == "POST"):
        id_pertandingan = request.POST.get("id_pertandingan")
        request.session['id_pertandingan'] = id_pertandingan
                
        query_selected = f"""
            SELECT S.Nama, S.id_stadium, T.id_pertandingan, p.Start_Datetime, p.End_Datetime
            FROM Stadium AS S, tim_pertandingan as t, pertandingan as p
            WHERE S.id_stadium=p.stadium AND p.id_pertandingan='{id_pertandingan}';
        """
        query_all = f"""
                SELECT S.Nama, S.id_stadium
                FROM Stadium AS S;
            """
        cur.execute(query_selected)
        data_selected = fetch(cur)
        
        cur.execute(query_all)
        data_all = fetch(cur)
        response = {'data_all': data_all, 'data_selected': data_selected,}
        return render(request, 'update_dropdown_stadium.html', response)
    
def update_create_pertandingan(request):
    if (request.method == "POST"):
        nama_stadium = request.POST.get("stadium")
        tanggal = request.POST.get("tanggal")
        print('haha')
        print(nama_stadium)
        print(tanggal)
        request.session['nama_stadium'] = nama_stadium
        request.session['tanggal'] = tanggal
        id_pertandingan = request.session.get('id_pertandingan')

        query_wasit = """
        SELECT nama_depan||' '||nama_belakang as nama, w.id_wasit
        FROM wasit as w, non_pemain
        WHERE NON_PEMAIN.id = w.id_wasit;
        """
        query_tim = f"select nama_tim from tim_manajer natural join peminjaman inner join stadium on peminjaman.id_stadium=stadium.id_stadium where stadium.id_stadium='{nama_stadium}';"

        # qwasitutama = f"""
        # SELECT DISTINCT n.nama_depan||' '||n.nama_belakang as nama, w.id_wasit
        # FROM wasit as w, non_pemain as n, pertandingan as p, wasit_bertugas as t
        # WHERE (n.id = w.id_wasit AND T.id_wasit=w.id_wasit 
        # AND n.id = T.id_wasit AND p.id_pertandingan=T.id_pertandingan 
        # AND p.id_pertandingan='{id_pertandingan}' 
        # AND t.posisi_wasit='utama');
        # """
        # qwasitpembantu= f"""
        # SELECT DISTINCT n.nama_depan||' '||n.nama_belakang as nama, w.id_wasit
        # FROM wasit as w, non_pemain as n, pertandingan as p, wasit_bertugas as t
        # WHERE (n.id = w.id_wasit AND T.id_wasit=w.id_wasit 

biru/templates/create_pertandingan.html
<!-- <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>U-LEAGUE</title>
  <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css">
</head>
<body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>

    <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a href="#" class="navbar-brand">U-LEAGUE</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="#">Dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Mengelola Tim</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Peminjaman Stadium</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">List Pertandingan</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">History Rapat</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Logout</a>
          </li>
        </ul>
      </div>
    </nav>
  </header>
    <h2 style="text-align: center;">BUAT PERTANDINGAN</h2>
	<div class = "kondisi_buat_pertandingan">
        <br>
        <br>
		
        
        <label for = "wasit_utama_dropdown">Pilih Wasit Utama: </label>
        <select class="form-select" aria-label="Default select example" name = "wasit_utama_dropdown">
            {% for item in data_w %}
                <option value="{{ item }}">{{ item.nama }}</option>
            {% endfor %}
        </select>
        <br>
        <label for = "wasit_pembantu_dropdown">Pilih Wasit Pembantu/Hakim Garis 1:</label>
        <select class="form-select" aria-label="Default select example" name = "wasit_pembantu1_dropdown">
            {% for item in data_w %}
                <option value="{{ item }}">{{ item.nama }}</option>
            {% endfor %}
        </select>
        <br>
        <label for = "wasit_pembantu_dropdown">Pilih Wasit Pembantu/Hakim Garis 2:</label>
        <select class="form-select" aria-label="Default select example" name = "wasit_pembantu2_dropdown">
            {% for item in data_w %}
            <option value="{{ item }}">{{ item.nama }}</option>
            {% endfor %}
        </select>
        <br>
        <label for = "wasit_cadangan_dropdown">Pilih Wasit Cadangan:</label>
        <select class="form-select" aria-label="Default select example" name = "wasit_cadangan_dropdown">
            {% for item in data_w %}
            <option value="{{ item }}">{{ item.nama }}</option>
            {% endfor %}
        </select>
        <br>
        <label for = "tim1_dropdown">Pilih Tim 1:</label>
        <select class="form-select" aria-label="Default select example" name = "tim1_dropdown">
            {% for item in data_t %}
            <option value="{{ item }}">{{ item.nama_tim }}</option>
            {% endfor %}
        </select>
        <br>
        <label for = "tim2_dropdown">Pilih Tim 2:</label>
        <select class="form-select" aria-label="Default select example" name = "tim2_dropdown">
            {% for item in data_t %}
            <option value="{{ item }}">{{ item.nama_tim }}</option>
            {% endfor %}
        </select>
          <br>
          <br>
		<button type = "button" class = "btn btn-primary">SUBMIT</button><br><br>
	</div>
</body>
</html> -->

<!-- BASTD SUCIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII -->

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>U-LEAGUE</title>
  <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css">
</head>
<body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>

    <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a href="#" class="navbar-brand">U-LEAGUE</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="#">Dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Mengelola Tim</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Peminjaman Stadium</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">List Pertandingan</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">History Rapat</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="#">Logout</a>
          </li>
        </ul>
      </div>
    </nav>
  </header>

  <h2 style="text-align: center;">BUAT PERTANDINGAN</h2>
	<form method="POST" action="submit_create_pertandingan">
    {% csrf_token %}
    <label for="wasitutama">Pilih Wasit Utama: </label>
    <select name="wasitutama" id="wasitutama">
    {% for item in data_w %}
        <option value="{{ item.id_wasit }}">{{ item.nama }}</option>
    {% endfor %}
    </select>
    <br>
    <label for="wasitpembantu1">Pilih Wasit Pembantu/Hakim Garis 1: </label>
    <select name="wasitpembantu1" id="wasitpembantu1">
    {% for item in data_w %}
      <option value="{{ item.id_wasit }}">{{ item.nama }}</option>
    {% endfor %}
    </select>
    <br>

    <label for="wasitpembantu2">Pilih Wasit Pembantu/Hakim Garis 2: </label>
    <select name="wasitpembantu2" id="wasitpembantu2">
    {% for item in data_w %}
      <option value="{{ item.id_wasit }}">{{ item.nama }}</option>
    {% endfor %}
    </select>
    <br>

    <label for="wasitcadangan">Pilih Wasit Cadangan: </label>
    <select name="wasitcadangan" id="wasitcadangan">
    {% for item in data_w %}
      <option value="{{ item.id_wasit }}">{{ item.nama }}</option>
    {% endfor %}
    </select>
    <br>

    <label for="tim1">Pilih Tim 1: </label>
    <select name="tim1" id="tim1">
      {% for item in data_t %}
      <option value="{{ item.nama_tim }}">{{ item.nama_tim }}</option>
      {% endfor %}
    </select>
    <br>

    <label for="tim2">Pilih Tim 2: </label>
    <select name="tim2" id="tim2">
      {% for item in data_t %}
      <option value="{{ item.nama_tim }}">{{ item.nama_tim }}</option>
      {% endfor %}
    </select>
    <br>

    <button type="submit" class="btn btn-primary">SUBMIT</button>

</form>
</body>
</html>

biru/templates/data_list_pertandingan.html
{% extends 'base.html' %} {% block meta %}
<title>List Pertandingan</title>
{% endblock meta %} {% block content %}
<div class="container align-center">
  <h1 class="subtitle text-center">List Pertandingan</h1>
  {% if message != "" %}
  <div class="text-center">{{ message }}</div>
  {% endif %}
  <div class="table-responsive">
    <table class="table table-bordered text-center">
      <thead>
        <tr>
          <th>GRUP A</th>
          <th>ACTION</th>
        </tr>
      </thead>
      <tbody>
        {% for item in data_1 %}
        <tr>
          <td>{{ item.nama_tim_a }} VS {{ item.nama_tim_b }}</td>
          <td>
            <form action = "{% url 'biru:update_dropdown_stadium' %}" method="POST">
              {% csrf_token %}
              <input type="hidden" name="id_pertandingan" value="{{ item.id_pertandingan }}">
              <button class="siruco-button" name='details' type="submit">Update</button>
            </form>
            <form action = "{% url 'biru:delete_pertandingan' %}" method="POST">
              {% csrf_token %}
              <input type="hidden" name="id_pertandingan" value="{{ item.id_pertandingan }}">
              <button class="siruco-button" name='details' type="submit">Delete</button>
            </form>
          </td>
        </tr>
        {% endfor %}
      </tbody>
      <thead>
        <tr>
          <th>GRUP B</th>
          <th>ACTION</th>
        </tr>
      </thead>
      <tbody>
        {% for item in data_2 %}
        <tr>
          <td>{{ item.nama_tim_a }} VS {{ item.nama_tim_b }}</td>
          <td>
            <form action = "{% url 'biru:update_dropdown_stadium' %}" method="POST">
              {% csrf_token %}
              <input type="hidden" name="id_pertandingan" value="{{ item.id_pertandingan }}">
              <button class="siruco-button" name='details' type="submit">Update</button>
            </form>
            <form action = "{% url 'biru:delete_pertandingan' %}" method="POST">
              {% csrf_token %}
              <input type="hidden" name="id_pertandingan" value="{{ item.id_pertandingan }}">
              <button class="siruco-button" name='details' type="submit">Delete</button>
            </form>
          </td>
        </tr>
        {% endfor %}
      </tbody>
      <thead>
        <tr>
          <th>GRUP C</th>
          <th>ACTION</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>? VS ?</td>
          <td>
            <a href="dropdown_stadium">[add]</a>
          </td>
        </tr>
      </tbody>
      <thead>
        <tr>
          <th>GRUP D</th>
          <th>ACTION</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>? VS ?</td>
          <td>
            <a href="dropdown_stadium">[add]</a>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
{% endblock content %}

biru/templates/data_list_waktu.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>U-LEAGUE</title>
  <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css">
</head>
<body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>

    <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a href="#" class="navbar-brand">U-LEAGUE</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="#">Dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Mengelola Tim</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Peminjaman Stadium</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">List Pertandingan</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">History Rapat</a>
          </li>

<!--      NAVBAR PENONTON
          <li class="nav-item">
            <a class="nav-link" href="#">Pembelian Tiket</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">List Pertandingan</a>
          </li>

          NAVBAR PANITIA
          <li class="nav-item">
            <a class="nav-link" href="#">Rapat</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Manage Pertandingan</a>
          </li>
           -->
          <li class="nav-item">
            <a class="nav-link" href="#">Logout</a>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  <br>
	<div class = "kondisi_sudah_ada">
		<table class = "table table-bordered">
			<thead class = "table-light">
				<tr><th scope="col" colspan="2" style="text-align: center;">LIST WAKTU STADIUM JAKARTA INTERNATIONAL STADIUM</th></tr>
				<tr>
					<th scope="col">LIST WAKTU</th>
					<th scope="col">ACTION</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>11.00 - 13.00</td>
					<td>DIPESAN</td>
				</tr>
				<tr>
					<td>07.00 - 09.00</td>
                    <td>
                        <a href="#">NEXT</a>
                    </td>
				</tr>
			</tbody>
		</table><br>
	</div>
</body>
</html>

biru/templates/update_dropdown_stadium.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>U-LEAGUE</title>
  <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css">
</head>
<body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>

    <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a href="#" class="navbar-brand">U-LEAGUE</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="#">Dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Mengelola Tim</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Peminjaman Stadium</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">List Pertandingan</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">History Rapat</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="#">Logout</a>
          </li>
        </ul>
      </div>
    </nav>
  </header>

  <h2 style="text-align: center;">PEMBUATAN PERTANDINGAN</h2>
  <form method="POST" action="update_create_pertandingan">
    {% csrf_token %}
    <label for="stadium">Stadium: </label>
    <select name="stadium" id="stadium">
      <option selected value="{{ data_selected.0.id_stadium }}">{{ data_selected.0.nama }}</option>
      {% for item in data_all %}
        <option value="{{ item.id_stadium }}" data-start-datetime="{{ item.start_datetime }}">{{ item.nama }}</option>
      {% endfor %}
    </select>
    <br>
    <label for="tanggal">Tanggal:</label>
    <input type="date" name="tanggal" id="tanggal">
    <br>
    <p id="selected-start-datetime"></p> <!-- Element to display the selected start datetime -->
    <br>
    <button type="submit" class="btn btn-primary">NEXT</button>
  </form>
  
  <script>
    // JavaScript code to display the selected start datetime
    const stadiumSelect = document.getElementById('stadium');
    const selectedStartDatetime = document.getElementById('selected-start-datetime');
  
    stadiumSelect.addEventListener('change', function() {
      const selectedOption = stadiumSelect.options[stadiumSelect.selectedIndex];
      const startDatetime = selectedOption.getAttribute('data-start-datetime');
      selectedStartDatetime.textContent = startDatetime;
    });
  </script>
  

</form>
</body>
</html>