biru/urls.py
#url routing
from biru.views import *
from django.urls import path

app_name = 'biru'

urlpatterns = [
    path('data_list_pertandingan', data_list_pertandingan, name='data_list_pertandingan'),
    path('dropdown_stadium', dropdown_stadium, name='dropdown_stadium'),
    path('data_list_waktu', data_list_waktu, name='data_list_waktu'),
    path('create_pertandingan', create_pertandingan, name='create_pertandingan'),
    path('delete', delete_pertandingan, name="delete_pertandingan"),
    path('submit_create_pertandingan', submit_create_pertandingan, name='submit_create_pertandingan'),
    path('update_dropdown_stadium', update_dropdown_stadium, name='update_dropdown_stadium'),
    path('update_create_pertandingan', update_create_pertandingan, name='update_create_pertandingan'),
    path('update_submit_create_pertandingan', update_submit_create_pertandingan, name='update_submit_create_pertandingan'),
]

pink/urls.py
from django.urls import path
from pink.views import index, pinjam_stadium, pinjam_stadium_form, tambah_peminjaman_stadium, mulai_rapat, isi_rapat, \
    process_isi_rapat

app_name = 'pink'

urlpatterns = [
    path('', index, name='index'),
    path('/pinjam_stadium/', pinjam_stadium, name='pinjam_stadium'),
    path('/pinjam_stadium/form/', pinjam_stadium_form, name='pinjam_stadium_form'),
    path('/tambah_peminjaman_stadium/', tambah_peminjaman_stadium, name='tambah_peminjaman_stadium'),
    path('/mulai_rapat/<uuid:pertandingan_id>/', isi_rapat, name='mulai_rapat_id'),
    path('/mulai_rapat/', mulai_rapat, name='mulai_rapat'),
    path('/process_isi_rapat/', process_isi_rapat, name='process_isi_rapat'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pink', include('pink.urls')),
    path('', include('putih.urls')),
    path('krem/', include('krem.urls')),
    path('putih/', include('putih.urls')),
    path('hijau/', include('hijau.urls')),
    path('biru/', include('biru.urls')),
]

pink/models.py
from django.db import models

# Create your models here.

pink/views.py
from django.shortcuts import render
import psycopg2
import psycopg2.extras
import json
from django.http import HttpResponse, HttpResponseNotAllowed, HttpResponseBadRequest, HttpResponseRedirect, JsonResponse, QueryDict
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
import uuid

from putih.decorators.logged_in_decorators import login_required, login_required_as_role

# Create your views here.
conn = psycopg2.connect(database=settings.DATABASE_NAME,
                        user=settings.DATABASE_USER,
                        password=settings.DATABASE_PASSWORD,
                        host=settings.DATABASE_HOST,
                        port=settings.DATABASE_PORT,
                        )

cur = conn.cursor()

def index(request):
    return render(request, 'index.html')

@login_required
@login_required_as_role('manajer')
def pinjam_stadium(request):
    query = f"SELECT nama, start_datetime, end_datetime FROM peminjaman, stadium WHERE peminjaman.id_stadium = stadium.id_stadium;"
    cur.execute(query)
    res = cur.fetchall()
    context = {'peminjaman_list': res}
    return render(request, 'peminjaman-stadium.html', context)

@login_required
@login_required_as_role('manajer')
def pinjam_stadium_form(request):
    query = "SELECT * FROM stadium"
    cur.execute(query)
    res = cur.fetchall()
    context = {'stadium_list' : res}
    return render(request, 'peminjaman-stadium-form.html', context)

@login_required
@login_required_as_role('manajer')
def tambah_peminjaman_stadium(request):
    id_manajer = request.COOKIES.get("id_role")
    stadium = request.POST['stadium']
    start_datetime = request.POST['start_date']
    end_datetime = request.POST['end_date']
    print(request.POST)
    try:
        cur.execute(
            "INSERT INTO peminjaman (id_manajer, start_datetime, end_datetime, id_stadium) VALUES (%s, %s, %s, %s);",
            [id_manajer, start_datetime, end_datetime, stadium])
        conn.commit()
        return HttpResponse("Berhasil")
    except Exception as e:
        conn.rollback()
        return HttpResponseBadRequest(e)
    return render(request, 'index.html')

@login_required
@login_required_as_role('panitia')
def mulai_rapat(request):
    query = """
            SELECT DISTINCT ON (B.id_pertandingan) B.id_pertandingan, A.nama_tim AS nama_tim_a, B.nama_tim AS nama_tim_b, P.start_datetime, P.end_datetime, S.nama AS nama_stadium
            FROM tim_pertandingan AS A
            JOIN tim_pertandingan AS B ON A.id_pertandingan = B.id_pertandingan AND A.nama_tim != B.nama_tim
            JOIN pertandingan AS P ON A.id_pertandingan = P.id_pertandingan
            JOIN stadium AS S ON P.stadium = S.id_stadium
            WHERE NOT EXISTS (
                SELECT 1
                FROM rapat
                WHERE rapat.id_pertandingan = A.id_pertandingan
            );
                """
    cur.execute(query)
    data = cur.fetchall()
    context = {'pertandingan_list': data}
    return render(request, 'mulai-rapat.html', context)

@login_required
@login_required_as_role('panitia')
def isi_rapat(request, pertandingan_id):
    query = """
        SELECT DISTINCT ON (B.id_pertandingan) B.id_pertandingan, A.nama_tim AS nama_tim_a, B.nama_tim AS nama_tim_b
        FROM tim_pertandingan AS A, tim_pertandingan AS B
        WHERE A.id_pertandingan = B.id_pertandingan AND A.nama_tim != B.nama_tim AND A.id_pertandingan = %s;
    """

    cur.execute(query, [str(pertandingan_id)])
    data = cur.fetchone()
    return render(request, 'isi-rapat.html', {'pertandingan': data})

@login_required
@login_required_as_role('panitia')
def process_isi_rapat(request):
    id_pertandingan = request.POST.get('pertandinganId')
    hasil_rapat = request.POST.get('isiRapat', '')
    perwakilan_panitia = request.COOKIES.get("id_role")
    cur.execute("""
            SELECT DISTINCT ON (B.id_pertandingan)
    B.id_pertandingan,
    A.nama_tim AS nama_tim_a,
    B.nama_tim AS nama_tim_b,
    MA.id_manajer AS id_manajer_a,
    MB.id_manajer AS id_manajer_b,
    P.start_datetime
FROM
    tim_pertandingan AS A
    JOIN tim_pertandingan AS B ON A.id_pertandingan = B.id_pertandingan AND A.nama_tim != B.nama_tim
    JOIN tim_manajer AS MA ON A.nama_tim = MA.nama_tim
    JOIN tim_manajer AS MB ON B.nama_tim = MB.nama_tim
    JOIN pertandingan AS P ON A.id_pertandingan = P.id_pertandingan
WHERE A.id_pertandingan=%s;
        """, [str(id_pertandingan)])
    fetch = cur.fetchone()
    data = {'data': fetch}
    print(data)
    manajer_tim_a = data.get('data')[3]
    manajer_tim_b = data.get('data')[4]
    datetime = data.get('data')[5]
    query ="""
    INSERT INTO rapat (id_pertandingan, datetime, perwakilan_panitia, manajer_tim_a, manajer_tim_b, isi_rapat)
VALUES (%s, %s, %s, %s, %s, %s);
    """

    try:
        cur.execute(query, [id_pertandingan, datetime, perwakilan_panitia, manajer_tim_a, manajer_tim_b, hasil_rapat])
        conn.commit()
        return HttpResponseRedirect(reverse('pink:mulai_rapat'))
    except Exception as e:
        conn.rollback()
        return HttpResponseBadRequest(e)
    return HttpResponseRedirect(reverse('pink:mulai_rapat'))

pink/templates/isi-rapat.html
{% extends "base.html" %}
{% load static %}

{% block title %}Peminjaman Stadium{% endblock %}

{% block content %}
<div class="container">
  <h1 class="mb-4">RAPAT PERTANDINGAN {{ pertandingan.1 }} vs {{ pertandingan.2 }}</h1>

  <form method="POST" action="{% url 'pink:process_isi_rapat' %}">
    {% csrf_token %}
    <input type="hidden" name="pertandinganId" value="{{ pertandingan.0 }}">
    <div class="mb-3">
      <label for="isiRapat" class="form-label">Isi Rapat:</label>
      <textarea name="isiRapat" class="form-control" id="isiRapat" rows="4"></textarea>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{% endblock %}

pink/templates/peminjaman-stadium-form.html
{% extends "base.html" %}
{% load static %}

{% block title %}Peminjaman Stadium{% endblock %}

{% block content %}
<div class="container">
  <h1 class="mb-4">PEMINJAMAN STADIUM</h1>

  <form id="peminjaman-form">
    {% csrf_token %}
    <div class="mb-3">
      <label for="stadium" class="form-label">Stadium:</label>
      <select id="stadium" name="stadium" class="form-select">
        {% for stadium in stadium_list %}
        <option value="{{ stadium.0 }}">{{ stadium.1 }}</option>
        {% endfor %}
      </select>
    </div>

    <div class="mb-3">
      <label for="start_date" class="form-label">Start Date:</label>
      <input type="date" id="start_date" name="start_date" class="form-control">
    </div>

    <div class="mb-3">
      <label for="end_date" class="form-label">End Date:</label>
      <input type="date" id="end_date" name="end_date" class="form-control">
    </div>

    <button type="button" id="submit-btn" class="btn btn-primary">Submit</button>
  </form>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  var csrf = "{{csrf_token}}"
  $(document).ready(function() {
    $('#submit-btn').click(function() {
      var formData = $('#peminjaman-form').serialize();

      $.ajax({
        url: "{% url 'pink:tambah_peminjaman_stadium' %}",
        type: "POST",
        headers: {
                    "X-CSRFToken": csrf
                },
        data: formData,
        success: function(response) {
          window.location.href =   "{% url 'pink:pinjam_stadium' %}"
        },
        error: function(xhr, errmsg, err) {
          // Handle the error response here
          console.log(xhr.status + ": " + xhr.responseText);
          window.alert("Sudah ada peminjaman di stadium tersebut pada tanggal yang dipilih")
          // You can display an error message or perform any other error handling
        }
      });
    });
  });
</script>
{% endblock %}

pink/templates/peminjaman-stadium.html
{% extends "base.html" %}
{% load static %}

{% block title %}Peminjaman Stadium{% endblock %}

{% block content %}
<div class="container text-center">
  <h1 class="mt-4 mb-3">List Peminjaman</h1>
  <table class="table table-striped">
    <colgroup>
      <col style="width: 50%">
      <col style="width: 50%">
    </colgroup>
    <thead>
      <tr>
        <th scope="col">Stadium</th>
        <th scope="col">Waktu</th>
      </tr>
    </thead>
    <tbody>
      {% for item in peminjaman_list %}
      <tr>
        <td>{{ item.0 }}</td>
        <td>{{ item.1 }} - {{ item.2 }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  <button class="btn btn-primary" onclick="location.href='form/'">Pesan</button>
</div>
{% endblock %}