biru/urls.py
#url routing
from biru.views import *
from django.urls import path

app_name = 'biru'

urlpatterns = [
    path('data_list_pertandingan', data_list_pertandingan, name='data_list_pertandingan'),
    path('dropdown_stadium', dropdown_stadium, name='dropdown_stadium'),
    path('data_list_waktu', data_list_waktu, name='data_list_waktu'),
    path('create_pertandingan', create_pertandingan, name='create_pertandingan'),
    path('delete', delete_pertandingan, name="delete_pertandingan"),
    path('submit_create_pertandingan', submit_create_pertandingan, name='submit_create_pertandingan'),
    path('update_dropdown_stadium', update_dropdown_stadium, name='update_dropdown_stadium'),
    path('update_create_pertandingan', update_create_pertandingan, name='update_create_pertandingan'),
    path('update_submit_create_pertandingan', update_submit_create_pertandingan, name='update_submit_create_pertandingan'),
]

hijau/urls.py
from hijau.views import *
from django.urls import path

app_name = "hijau"

urlpatterns = [
    path('', home, name="home"),
    path('create-tim', create_tim, name='create-tim'),
    path('update-captain', update_captain, name='update-captain'),
    path('delete-pemain', delete_pemain, name='delete-pemain'),
    path('add-pemain', add_pemain, name='add-pemain'),
    path('add-pelatih', add_pelatih, name='add-pelatih'),
    path('insert-pelatih', insert_pelatih, name='insert-pelatih-into-tim'),
    path('insert-pemain-into-tim', insert_pemain_into_tim, name='insert-pemain-into-tim'),
    path('update-pelatih', update_pelatih, name='update-pelatih'),
]   

krem/urls.py
from django.urls import path

from krem.views import *

app_name = "krem"

urlpatterns = [
    path('', index, name="index"),
    path('pembelian_tiket', pembelian_tiket, name="pembelian_tiket"),
    path('pembelian_tiket2', pembelian_tiket2, name="pembelian_tiket2"),
    path('pembelian_tiket3', pembelian_tiket3, name="pembelian_tiket3"),
    path('pembelian_tiket4', pembelian_tiket4, name="pembelian_tiket4"),
    path('list_pertandingan_penonton', list_pertandingan_penonton, name="list_pertandingan_penonton"),
    path('list_pertandingan_manajer', list_pertandingan_manajer, name="list_pertandingan_manajer"),
    path('history_rapat', history_rapat, name="history_rapat"),
    path('isi_rapat', isi_rapat, name="isi_rapat")
]

pink/urls.py
from django.urls import path
from pink.views import index, pinjam_stadium, pinjam_stadium_form, tambah_peminjaman_stadium, mulai_rapat, isi_rapat, \
    process_isi_rapat

app_name = 'pink'

urlpatterns = [
    path('', index, name='index'),
    path('/pinjam_stadium/', pinjam_stadium, name='pinjam_stadium'),
    path('/pinjam_stadium/form/', pinjam_stadium_form, name='pinjam_stadium_form'),
    path('/tambah_peminjaman_stadium/', tambah_peminjaman_stadium, name='tambah_peminjaman_stadium'),
    path('/mulai_rapat/<uuid:pertandingan_id>/', isi_rapat, name='mulai_rapat_id'),
    path('/mulai_rapat/', mulai_rapat, name='mulai_rapat'),
    path('/process_isi_rapat/', process_isi_rapat, name='process_isi_rapat'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pink', include('pink.urls')),
    path('', include('putih.urls')),
    path('krem/', include('krem.urls')),
    path('putih/', include('putih.urls')),
    path('hijau/', include('hijau.urls')),
    path('biru/', include('biru.urls')),
]

putih/urls.py
#url routing
from putih.views import *
from django.urls import path
from django.contrib.auth import views as auth_views



app_name = 'putih'

urlpatterns = [
    path('', login, name='open'),
    path('dashboard', dashboard, name='dashboard'),
    path('login', login, name='login'),
    path('login.php', login, name='loginphp'),
    path('register', register, name='register'),
    path('register.php', register, name='register.php'),
    path('logout', logout, name='logout'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- <link rel="stylesheet" href="{% static 'css/style.css' %}"> -->
  <title>U-LEAGUE</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  </head>
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

    <header>
    {% if request.COOKIES.username %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a href="#" class="navbar-brand">U-LEAGUE Hi, {{ request.COOKIES.username }}! Logged in as {{ request.COOKIES.role }}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'putih:dashboard' %}">Dashboard</a>
          </li>
          
          {% if request.COOKIES.role == "manajer" %}

          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'hijau:home' %}">Mengelola Tim</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'pink:pinjam_stadium' %}">Peminjaman Stadium</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'krem:list_pertandingan_manajer' %}">List Pertandingan</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'krem:history_rapat' %}">History Rapat</a>
          </li> 

          {% endif %}

          {% if request.COOKIES.role == "penonton" %}

          <li class="nav-item">
            <a class="nav-link" href="{% url 'krem:pembelian_tiket' %}">Pembelian Tiket</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'krem:list_pertandingan_penonton' %}">List Pertandingan</a>
          </li> 

          {% endif %}


          {% if request.COOKIES.role == "panitia" %}

          <li class="nav-item">
            <a class="nav-link" href="{% url 'pink:mulai_rapat' %}">Rapat</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'biru:data_list_pertandingan' %}">Manage Pertandingan</a>
          </li>

          {% endif %}

          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'putih:logout' %}">Logout</a>
          </li>
        </ul>
      </div>
    </nav>
    {% endif %}
  </header>

  {% block content %}
  {% endblock content %}

</body>

</html>