biru/urls.py
#url routing
from biru.views import *
from django.urls import path

app_name = 'biru'

urlpatterns = [
    path('data_list_pertandingan', data_list_pertandingan, name='data_list_pertandingan'),
    path('dropdown_stadium', dropdown_stadium, name='dropdown_stadium'),
    path('data_list_waktu', data_list_waktu, name='data_list_waktu'),
    path('create_pertandingan', create_pertandingan, name='create_pertandingan'),
    path('delete', delete_pertandingan, name="delete_pertandingan"),
    path('submit_create_pertandingan', submit_create_pertandingan, name='submit_create_pertandingan'),
    path('update_dropdown_stadium', update_dropdown_stadium, name='update_dropdown_stadium'),
    path('update_create_pertandingan', update_create_pertandingan, name='update_create_pertandingan'),
    path('update_submit_create_pertandingan', update_submit_create_pertandingan, name='update_submit_create_pertandingan'),
]

hijau/urls.py
from hijau.views import *
from django.urls import path

app_name = "hijau"

urlpatterns = [
    path('', home, name="home"),
    path('create-tim', create_tim, name='create-tim'),
    path('update-captain', update_captain, name='update-captain'),
    path('delete-pemain', delete_pemain, name='delete-pemain'),
    path('add-pemain', add_pemain, name='add-pemain'),
    path('add-pelatih', add_pelatih, name='add-pelatih'),
    path('insert-pelatih', insert_pelatih, name='insert-pelatih-into-tim'),
    path('insert-pemain-into-tim', insert_pemain_into_tim, name='insert-pemain-into-tim'),
    path('update-pelatih', update_pelatih, name='update-pelatih'),
]   

mengelolatim/urls/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    # Add more URL patterns here
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pink', include('pink.urls')),
    path('', include('putih.urls')),
    path('krem/', include('krem.urls')),
    path('putih/', include('putih.urls')),
    path('hijau/', include('hijau.urls')),
    path('biru/', include('biru.urls')),
]

hijau/views.py
import json
from django.shortcuts import render
import psycopg2
import psycopg2.extras
from django.conf import settings
from django.http import HttpResponseBadRequest, HttpResponse, HttpResponseRedirect, HttpResponseNotAllowed, JsonResponse, QueryDict
from django.urls import reverse
from putih.decorators.logged_in_decorators import login_required_as_role, login_required
from putih.views import json_format


# Create your views here.
conn = psycopg2.connect(database=settings.DATABASE_NAME, 
                        user=settings.DATABASE_USER, 
                        password=settings.DATABASE_PASSWORD,
                        host=settings.DATABASE_HOST, 
                        port=settings.DATABASE_PORT, 
                        )

cur = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)

@login_required
@login_required_as_role('manajer')
def home(request):
    tim = get_tim_from_manajer(request.COOKIES.get('id_role'))
    if(tim != []):
        result = {"data":[]}
        for i in tim:
            result["data"].append({
                "tim": i,
                "pelatih": get_pelatih_from_tim(i.get("nama_tim")),
                "pemain": get_pemain_from_tim(i.get("nama_tim")),
            })
        return render(request, "tim.html", context=result)
    
    return render(request, 'mengelola_tim.html')

@login_required
@login_required_as_role('manajer')
def create_tim(request):
    if (request.method == "POST"):
        nama_tim = request.POST.get('nama-tim')
        nama_univ = request.POST.get('nama-univ')
        try:
            cur.execute('INSERT INTO TIM VALUES(%s, %s)', [nama_tim, nama_univ, ])
            conn.commit()

            cur.execute('INSERT INTO TIM_MANAJER VALUES(%s, %s)',[request.COOKIES.get('id_role'), nama_tim, ])
            conn.commit()

            return HttpResponse('mantap')
        except Exception as e:
            conn.rollback()
            print(e)
            return HttpResponse(e)
    
    return HttpResponseNotAllowed("Invalid request method. Please use supported request method.")

@login_required
@login_required_as_role('manajer')
def add_pemain(request):
    cur.execute("SELECT * FROM PEMAIN WHERE nama_tim IS NULL")
    result = cur.fetchall()
    json_format(result)
    data = {
        "data":result
    }
    return render(request, "pemilihan_pemain.html", context=data)

@login_required
@login_required_as_role('manajer')
def add_pelatih(request):
    cur.execute("SELECT * FROM PELATIH P JOIN NON_PEMAIN N ON P.id_pelatih = N.id JOIN SPESIALISASI_PELATIH S ON P.id_pelatih = S.id_pelatih WHERE nama_tim IS NULL")
    result = cur.fetchall()
    json_format(result)
    data = {
        "data":result
    }
    return render(request, "pemilihan_pelatih.html", context=data)

@login_required
@login_required_as_role('manajer')
def insert_pemain_into_tim(request):
    if (request.method == 'POST'):

        payload = QueryDict(request.body)
        id_pemain = payload.get('id_pemain')
        tim = get_tim_from_manajer(request.COOKIES.get('id_role'))
        try:
            psycopg2.extras.register_uuid()
            cur.execute("UPDATE PEMAIN SET nama_tim=%s WHERE id_pemain=%s",[tim[0]['nama_tim'], id_pemain, ])
            conn.commit()
            return HttpResponse("Success")
        except Exception as e:
            conn.rollback()
            print(e)
            return HttpResponseBadRequest("Failed to update pemain")

@login_required
@login_required_as_role('manajer')
def insert_pelatih(request):
    if (request.method == 'POST'):
        payload = QueryDict(request.body)
        id_pelatih = payload.get('id_pelatih')
        tim = get_tim_from_manajer(request.COOKIES.get('id_role'))
        try:
            psycopg2.extras.register_uuid()
            cur.execute("UPDATE PELATIH SET nama_tim=%s WHERE id_pelatih=%s",[tim[0]['nama_tim'], id_pelatih, ])
            conn.commit()
            return HttpResponse("Success")
        except Exception as e:
            conn.rollback()
            print(e)
        return HttpResponseBadRequest("Failed to update pelatih")

@login_required
@login_required_as_role('manajer')
def update_pelatih(request):
    if(request.method == "POST"):
        payload = QueryDict(request.body)
        id_pelatih = payload.get('id_pelatih')
        try:
            cur.execute("UPDATE PELATIH SET nama_tim=NULL WHERE id_pelatih=%s",[id_pelatih, ])
            conn.commit()
            return HttpResponse("Success")
        except Exception as e:
            conn.rollback()
            print(e)
            return HttpResponse("Unsuccessful")
    return HttpResponseNotAllowed("Invalid request method. Please use supported request method.")


@login_required
@login_required_as_role('manajer')
def delete_pemain(request):
    if(request.method == "DELETE"):
        payload = QueryDict(request.body)
        id_pemain = payload.get('id_pemain')
        tim = get_tim_from_manajer(request.COOKIES.get('id_role'))
        try:
            cur.execute("UPDATE PEMAIN SET nama_tim = NULL WHERE id_pemain=%s",[tim[0]['id_pemain'], ])
            conn.commit()
        except Exception as e:
            conn.rollback()
            print(e)
            return HttpResponse("Unsuccessful")
        return HttpResponse("Success!")

    return HttpResponseNotAllowed("Invalid request method. Please use supported request method.")

@login_required
@login_required_as_role('manajer')
def update_captain(request):
    if(request.method == "POST"):
        payload = QueryDict(request.body)
        id_pemain = payload.get('id_pemain')
        try:
            cur.execute("UPDATE PEMAIN SET is_captain=TRUE WHERE id_pemain=%s",[id_pemain, ])
            conn.commit()
        except Exception as e:
            conn.rollback()
            return HttpResponse("User is already a captain!")
        return HttpResponse("Success!")
    return HttpResponseNotAllowed("Invalid request method. Please use supported request method.")


def get_tim_from_manajer(id_manajer):
    cur.execute("SELECT * FROM TIM_MANAJER WHERE id_manajer = %s", [id_manajer, ])
    result = cur.fetchall()
    json_format(result)
    return result

def get_pemain_from_tim(nama_tim):
    cur.execute("SELECT * FROM PEMAIN WHERE nama_tim = %s", [nama_tim, ])
    result = cur.fetchall()
    json_format(result)
    return result

def get_pelatih_from_tim(nama_tim):
    cur.execute("SELECT * FROM PELATIH, NON_PEMAIN WHERE id = id_pelatih AND nama_tim = %s", [nama_tim, ])
    result = cur.fetchall()
    json_format(result)
    for i in range(len(result)):
        cur.execute("SELECT spesialisasi FROM SPESIALISASI_PELATIH WHERE id_pelatih = %s", [result[i]["id_pelatih"]])
        result[i]['spesialisasi'] = cur.fetchall()
    return result

mengelolatim/views.py
from django.shortcuts import render

# Create your views here.

hijau/templates/mengelola_tim.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Form Registrasi</title>
<style>
    /* CSS styles */
    
    body {
    font-family: Arial, sans-serif;
    background-color: #f2f2f2;
    background-image: url(https://a-static.besthdwallpaper.com/fifa-23-football-arena-wallpaper-3440x1440-102008_15.jpg);
    background-repeat: no-repeat;
    background-size: cover;
    height: 100vh;
    }

    .container {
    max-width: 400px;
    margin: 50px auto;
    padding: 20px;
    background-color: #fff;
    border-radius: 5px;
    text-align: center;
    }

    label {
    display: inline-block;
    font-size: 12px;
    margin-bottom: 10px;
    }

    input[type="text"] {
    width: 50%;
    padding: 5px;
    margin-bottom: 20px;
    border-radius: 5px;
    border: 1px solid #ccc;
    }

    input[type="submit"] {
    background-color: #1DA1F2;
    color: #fff;
    padding: 10px 20px;
    border: none;
    border-radius: 5px;
    cursor: pointer;
    }
</style>

<script>
    var url_to_create_tim = "{% url 'hijau:create-tim' %}"
    var url_to_tim = "{% url 'hijau:home' %}"
    var csrf = "{{csrf_token}}"
    $(document).ready(function(){
        $("#submit").click(function(){
            $.ajax({
                url: url_to_create_tim,
                type: "POST",
                headers: {
                    "X-CSRFToken": csrf
                },
                data: {
                    'csrfmiddlewaretoken': csrf,
                    "nama-tim": $("#nama-tim").val(),
                    "nama-univ": $("#nama-univ").val(),
                },
                success: function(data){
                    alert(data)
                    window.location.href = url_to_tim
                }
            })
        })
    })
</script>
{% endblock meta %}

{% block content %}
<div class="container">
    <h3>FORM REGISTRASI</h3>
    <div class="new">
        <label for="nama-tim">Nama Tim:</label>
        <input type="text" id="nama-tim" name="nama-tim">
    </div>

    <label for="nama-univ">Nama Universitas:</label>
    <input type="text" id="nama-univ" name="nama-univ">

    <button class="btn btn-primary" id="submit">Submit</button>
</div>
{% endblock content %}

hijau/templates/pemilihan_pelatih.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Form Registrasi</title>
<style>
    /* CSS styles */
    body {
        font-family: Arial, sans-serif;
        background-color: #cdeefd;
        background-image: url(https://a-static.besthdwallpaper.com/fifa-23-football-arena-wallpaper-3440x1440-102008_15.jpg);
        background-repeat: no-repeat;
        background-size: cover;
        height: 100vh;
    }
    .box {
        max-width: 400px;
        margin: 50px auto;
        padding: 20px;
        background-color: #fff;
        border-radius: 5px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
    }
    .box h3 {
        text-align: center;
    }
    .box label {
        display: block;
        margin-bottom: 10px;
    }
    .box select {
        width: 100%;
        padding: 10px;
        margin-bottom: 20px;
        border-radius: 5px;
        border: 1px solid #ccc;
    }


    .box input[type="submit"] {
        background-color: #1DA1F2;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        text-align: center;
    }

    .submit-container {
        width: 100%;
        text-align: center;
    }
</style>
<script>
    var csrf = "{{csrf_token}}"
    var url_insert_pelatih_into_tim = "{% url 'hijau:insert-pelatih-into-tim' %}"
    function addPelatih(id_pelatih){
        $.ajax({
            method: "POST",
            contentType: "application/json",
            url: url_insert_pelatih_into_tim,
            headers:{
                "X-CSRFToken": csrf
            },
            data:{
                'csrfmiddlewaretoken': csrf,
                "id_pelatih": id_pelatih
            },
            success: function(data){
                alert(data)
                window.location.reload
            }
        })
    }

    $(document).ready(function(){
        $("#submit-button").click(function(){
            const id_pelatih = $("#pelatih").val()
            addPelatih(id_pelatih)
        })
    })
</script>
{% endblock meta %}

{% block content %}
<div class="box">
    <h3>DAFTAR PELATIH</h3>
    <label for="pelatih">Pelatih yang mau didaftarkan:</label>
    <select id="pelatih" name="pelatih">
        {% for elem in data %}
            <option value="{{elem.id_pelatih}}">{{elem.nama_depan}} {{elem.nama_belakang}} - {{elem.spesialisasi}}</option>
        {% endfor %}
    </select>
    <div class="submit-container">
        <button type="button" id="submit-button">Submit</button>
    </div>
</div>
{% endblock content %}

hijau/templates/pemilihan_pemain.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Form Registrasi</title>
<style>
    /* CSS styles */
    body {
        font-family: Arial, sans-serif;
        background-color: #cdeefd;
        background-image: url(https://a-static.besthdwallpaper.com/fifa-23-football-arena-wallpaper-3440x1440-102008_15.jpg);
        background-repeat: no-repeat;
        background-size: cover;
        height: 100vh;
    }
    .box {
        max-width: 400px;
        margin: 50px auto;
        padding: 20px;
        background-color: #fff;
        border-radius: 5px;
        box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
    }
    .box h3 {
        text-align: center;
    }
    .box label {
        display: block;
        margin-bottom: 10px;
    }
    .box select {
        width: 100%;
        padding: 10px;
        margin-bottom: 20px;
        border-radius: 5px;
        border: 1px solid #ccc;
    }


    .box input[type="submit"] {
        background-color: #1DA1F2;
        color: #fff;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
        text-align: center;
    }

    .submit-container {
        width: 100%;
        text-align: center;
    }
</style>
<script>
    var csrf = "{{csrf_token}}"
    var url_create = "{% url 'hijau:insert-pemain-into-tim' %}"
    function addPemain(id_pemain){
        $.ajax({
            method: "POST",
            contentType: "application/json",
            url: url_create,
            headers:{
                "X-CSRFToken": csrf
            },
            data:{
                'csrfmiddlewaretoken': csrf,
                "id_pemain": id_pemain
            },
            success: function(data){
                alert(data)
                window.location.reload()
            }
        })
    }
    $(document).ready(function(){
        $("#submit-button").click(function(){
            const id_pemain = $("#pemain").val()
            addPemain(id_pemain)
        })
    })
    
</script>
{% endblock meta %}

{% block content %}
<div class="box">
    <h3>DAFTAR PEMAIN</h3>
    <label for="pemain">Pemain yang mau didaftarkan:</label>
    <select id="pemain" name="pemain">
        {% for elem in data %}
            <option value="{{elem.id_pemain}}">{{elem.nama_depan}} {{elem.nama_belakang}}</option>
        {% endfor %}
    </select>
    <div class="submit-container">
        <button type="button" id="submit-button">Submit</button>
    </div>
</div>
{% endblock content %}

hijau/templates/tim.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Form Registrasi</title>
<style>
    body {
      margin: 0;
      padding: 0;
      font-family: Arial, sans-serif;
      font-family: Arial, sans-serif;
      background-color: #cdeefd;
      background-image: url(https://a-static.besthdwallpaper.com/fifa-23-football-arena-wallpaper-3440x1440-102008_15.jpg);
      background-repeat: no-repeat;
      background-size: cover;
      height: 100vh;
    }
    
    h2 {
      font-size: 25px;
      font-weight: bold;
      margin-bottom: 10px;
      text-align: center;
      color: white;
    }
    h3 {
      font-size: 16px;
      font-weight: bold;
      margin-top: 30px;
      margin-bottom: 10px;
      text-align: center;
      color: white;
    }
    table {
      border-collapse: collapse;
      width: 100%;
    }
    th,
    td {
      text-align: left;
      padding: 8px;
      font-size: 12px;
      border: 1px solid #ddd;
      background-color: #f2f2f2;
    }
    th {
      background-color: #1DA1F2;
      font-weight: bold;
    }

    .button {
      font-size: 15px;
      background-color: #1DA1F2;
      padding: 5px;
      color: white;
      border: none;
      border-radius: 5px;
      cursor: pointer;
    }
</style>

<script>
    // $(document).ready(function(){
    //     if ("{{data.0.pelatih.id_pelatih}}" != "") $("#button-pelatih").hide()
    // })

    const url_update_captain = "{% url 'hijau:update-captain' %}"
    const url_delete_pemain = "{% url 'hijau:delete-pemain' %}"
    const url_add_pemain = "{% url 'hijau:add-pemain' %}"
    const url_home = "{% url 'hijau:home' %}"
    const url_add_pelatih = "{% url 'hijau:add-pelatih' %}"
    const url_delete_pelatih = "{% url 'hijau:update-pelatih' %}"
    const csrf = "{{csrf_token}}"

    function captainButton(idPemain){
        $.ajax({
            method: "POST",
            url: url_update_captain,
            headers:{
                'X-CSRFToken': csrf
            },
            data: {
                'csrfmiddlewaretoken': csrf,
                'id_pemain': idPemain,
            },
            success: function(data){
                alert(data)
                window.location.reload()
            }
        })
    }

    function deleteButton(idPemain){
        $.ajax({
            method: "DELETE",
            url: url_delete_pemain,
            headers:{
                'X-CSRFToken': csrf
            },
            data:{
                'csrfmiddlewaretoken': csrf,
                'id_pemain': idPemain
            },
            success: function(data){
                alert(data)
                window.location.reload()
            }
        })
    }

    function deleteButtonForPelatih(idPelatih){
        $.ajax({
            method: "POST",
            url: url_delete_pelatih,
            headers:{
                'X-CSRFToken': csrf
            },
            data:{
                'csrfmiddlewaretoken': csrf,
                'id_pelatih': idPelatih
            },
            success: function(data){
                alert(data)
                window.location.reload()
            }
        })
    }

</script>
{% endblock meta %}

{% block content %}
<div class="container" id="container">
    {% for elem in data %}
        <h2>Tim {{elem.tim.nama_tim}}</h2>
        <h3>Pemain</h3>
        <table>
            <thead>
                <tr>
                    <th>Nama Pemain</th>
                    <th>No HP</th>
                    <th>Tanggal Lahir</th>
                    <th>Is Captain</th>
                    <th>Posisi</th>
                    <th>NPM</th>
                    <th>Jenjang</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for data_pemain in elem.pemain %}
                    <tr>
                        <td>{{data_pemain.nama_depan}} {{data_pemain.nama_belakang}}</td>
                        <td>{{data_pemain.nomor_hp}}</td>
                        <td>{{data_pemain.tgl_lahir}}</td>
                        <td id = "{{data_pemain.id_pemain}}">{{data_pemain.is_captain}}</td>
                        <td>{{data_pemain.posisi}}</td>
                        <td>{{data_pemain.npm}}</td>
                        <td>{{data_pemain.jenjang}}</td>
                        <td>
                            <button class="button" onclick="captainButton('{{data_pemain.id_pemain}}')">Make Captain</button>
                            <button class="button button-danger" onclick="deleteButton('{{data_pemain.id_pemain}}')">Delete</button>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <h3>Pelatih</h3>
        <table>
            <thead>
                <tr>
                    <th>Nama</th>
                    <th>No HP</th>
                    <th>Email</th>
                    <th>Alamat</th>
                    <th>Spesialisasi</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for pelatih_elem in elem.pelatih %}
                <tr>
                    <td>{{pelatih_elem.nama_depan}} {{pelatih_elem.nama_belakang}}</td>
                    <td>{{pelatih_elem.nomor_hp}}</td>
                    <td>{{pelatih_elem.email}}</td>
                    <td>{{pelatih_elem.alamat}}</td>
                    <td>{{pelatih_elem.spesialisasi}}</td>
                        <td><button class="button button-danger" onclick="deleteButtonForPelatih('{{pelatih_elem.id_pelatih}}')">Delete</button></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <button class="button" onclick="window.location.href = url_add_pemain">Pemain</button>
        <button class="button" id = "button-pelatih" onclick="window.location.href = url_add_pelatih">Pelatih</button>
    {% endfor %}

</div>
{% endblock content %}